app/components/navigation/Footer.tsx
Closes #16 
Removes the copyright and reformats the CSS for the footer elements.
=> Remove Copyright

app/api/pathway/search/route.ts, app/components/navigation/CatalogDropdown.tsx, app/contexts/appContext/AppProvider.tsx, app/pathways/search/page.tsx, public/data/dataInterface.ts, public/data/staticData.ts
fix the displaying issues with the find pathways, haven't test the filter functions yet.
=> Findpathways

app/api/pathway/search/route.ts, app/components/navigation/CatalogDropdown.tsx, app/contexts/appContext/AppProvider.tsx, app/pathways/search/page.tsx, public/data/staticData.ts
fixed the catalog dropdown for navbar, set 2022-2023 as default and actually changes the app context when a different year is clicked
=> fix catalog dropdown

app/components/navigation/DropDownMenu.tsx, app/components/navigation/NavButton.tsx, app/components/navigation/NavigationBar.tsx
Made dropdown for courses and pathways
=> Drop down menu

app/components/navigation/NavigationBar.tsx, tailwind.config.js
Update the progress bars to use a different shade so it is not longer based around red. Currently set completed to a shade of green and in progress to a shade of orange.
=> Change Progress Bar Colors

.env, app/api/course/search/route.ts, app/components/course/CourseCard.tsx, app/components/course/CourseDropDownButton.tsx, app/components/course/SearchComponent.tsx, app/components/navigation/NavigationBar.tsx, app/contexts/actions.ts, app/contexts/appContext/AppProvider.tsx, app/contexts/appContext/AppReducer.tsx, app/courses/page.tsx, app/model/AppContextInterface.ts, app/model/CourseInterface.ts, public/data/dataInterface.ts, public/data/staticData.ts, tailwind.config.js
fix the sync between find course and my course page, so that my course update appropriately.
=> Findcourse

app/components/course/OfferTable.tsx, app/courses/[courseCode]/page.tsx
This mostly involved changing variable names and editing the use effect for the indiv course page.
=> Change Semester Offered Table to use new Interface

app/components/pathway/PathwayCard.tsx
Used a similar format to the course card link.
=> #59 Make pathway title a link to the pathway page

app/components/navigation/CatalogDropdown.tsx, app/contexts/appContext/AppProvider.tsx, app/pathways/[id]/page.tsx
Closes #103 
This prevents pages that rely on the catalog year from loading before the correct year is set.
=> #103 Set catalog year to blank until it gets loaded

app/components/course/OfferTable.tsx
Makes "Available" a check mark and "Unavailable" an X mark.
Closes #100
=> #100 Change Offered Table Text

app/pathways/[id]/page.tsx
It seems like it was a similar issue to what I was having with the catalog year use effect, so I also made the data fetch useEffect dependent on the pathway name.
=> #107 Fix Well Being: Body and Mind

app/components/course/SearchComponent.tsx, app/components/navigation/Footer.tsx, app/layout.tsx, app/pathways/search/page.tsx, tailwind.config.js
=> #110 Fix Max Screen Size

app/components/course/CourseDropDownButton.tsx
Closes #47 
also changes the dropdown design somewhat using Heroicons
https://github.com/user-attachments/assets/525791c6-bcde-4581-9a5f-805bb9ec3224
=> #47 Allow users to edit course state without removing the course

app/pathways/[id]/page.tsx
=> #108 Add Bookmark to Indiv Pathway Page

app/api/pathway/search/route.ts, app/components/pathway/PathwayCard.tsx
=> #105 Make Progress Bar Correspond to Course Status

app/components/course/CourseCard.tsx
Makes Course Title link stick to course title text, Made prereq text always render if it exists and added a UIA tag
Closes #121
=> #121 Course Card Flex Box Bugs, Prerequisite Render Bugs

app/pathways/page.tsx
Closes #127 
This makes it so that the matched button works on the my pathway page. If you change the catalog year you will need to refresh the page. That is something that will need to be implemented in a future PR. I also went and removed some unnecessary code
=> Implement matched button

app/components/pathway/PathwayCard.tsx
Pathway cards were missing keys which react needs. Added unique keys to the elements
=> Add keys to pathway card

app/pathways/[id]/page.tsx
=> #137 Fix runtime error when bookmarking in individial pathway page

app/api/pathway/search/route.ts, app/components/pathway/PathwayCard.tsx, app/components/pathway/PathwayPopup.tsx, app/contexts/appContext/AppProvider.tsx, app/contexts/appContext/AppReducer.tsx, app/globals.css, app/model/AppContextInterface.ts, app/pathways/page.tsx, app/pathways/search/page.tsx, components.json, components/ui/button.tsx, components/ui/dialog.tsx, lib/utils.ts, package-lock.json, package.json, tailwind.config.js
=> 133 Rebuild modal with shadcn

app/pathways/page.tsx
=> #136 Switched Default Behavior on My Pathways to Matched

app/pathways/[id]/page.tsx
=> #150 Remove Add to My Pathways Text

app/components/course/AttributeTag.tsx, app/components/course/CourseCard.tsx, app/components/course/CoursePopup.tsx, app/components/course/OfferedSemestersTag.tsx
=> #153 Add Course Modal

app/components/pathway/PathwayCard.tsx
Fixed this by replacing my z-based popup open with a stopPropagation based solution.
Closes #162
=> #162 Catalog Dropdown Bleeds into Pathway Card
